context("parseMinionOut")

test_that("parsing Minion output works", {
  pout <- parseMinionOut(out1)
  expect_equal(pout$`Parsing Time`, 0.001128)
  expect_equal(pout$`Setup Time`, 0.000509)
  expect_equal(pout$`First Node Time`, 0.000361)
  expect_equal(pout$`Initial Propagate`, 0.00037)
  expect_equal(pout$`First node time`, 8.4e-05)
  expect_equal(pout$`Solve Time`, 0.00266)
  expect_equal(pout$`Total Time`, 0.00475)
  expect_equal(pout$`Total System Time`, 0)
  expect_equal(pout$`Total Wall Time`, 0.004928)
  expect_equal(pout$`Maximum RSS (kB)`, 1496)
  expect_equal(pout$`Total Nodes`, 690)
  expect_equal(pout$`Problem solvable?`, FALSE)
  expect_equal(pout$`Solutions Found`, 0)
})
